### ISSUE TITLE
Incorrect nulls

### ISSUE THREAD

**Issue by Gemorroj** [php-stubs/woocommerce-stubs#10]
All `null` values have unnecessary backslash
for example 91 line:
```php
protected $meta_data = \null;
```

**Comment by szepeviktor** [comment]
Hello @Gemorroj!
Thank you for your report.
These stubs are automatically generated from WC source code.
I think the generator tool puts there those backslashes.
https://github.com/php-stubs/woocommerce-stubs/blob/master/composer.json#L17

**Comment by szepeviktor** [comment]
Please see https://stackoverflow.com/questions/55707481/why-can-null-be-written-with-a-backslash
