### ISSUE TITLE
woocommerce 6.0 stubs missing

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/woocommerce-stubs#12]
woocommerce 6.0 stubs missing

**Comment by szepeviktor** [comment]
Hello @kkmuffme! 👋 

WC 6.0 is not released yet.
https://github.com/woocommerce/woocommerce/tags

**Comment by thejamescollins** [comment]
Hi @szepeviktor, 

WooCommerce has today added the 6.0.0 tag: https://github.com/woocommerce/woocommerce/releases/tag/6.0.0

Thank you

**Comment by szepeviktor** [comment]
Thank you!
I'm also subscribed to their release feed and I talk to them regularly.

Packagist does not update!!! https://packagist.org/packages/woocommerce/woocommerce.json

**Comment by thejamescollins** [comment]
The WooCommerce composer package is [currently broken due to switching to a mono repo structure in WC 6.0](https://github.com/woocommerce/woocommerce/issues/31475#issuecomment-1004345153).

In the interim is it feasible to build the stubs from another source, such as a WordPress.org zip file perhaps?

**Comment by szepeviktor** [comment]
As you wish. But only this time.

**Comment by thejamescollins** [comment]
I'm happy to attempt a PR if you're open to accepting one as a one-off?

**Comment by szepeviktor** [comment]
Done 🍏 
https://github.com/php-stubs/woocommerce-stubs/releases/tag/v6.0.0

**Comment by thejamescollins** [comment]
Thank you very much @szepeviktor 💯

**Comment by timnolte** [comment]
@om4james & @szepeviktor it appears that this PR has broken the tags in the repo. Not all releases are being made available. It appears that only the latest patch release of each minor version are being tagged.

**Comment by szepeviktor** [comment]
> only the latest patch release of each minor version are being tagged

Yes, my release script does that.
https://github.com/php-stubs/woocommerce-stubs/issues/13#issuecomment-1113930264

Patch versions - in theory - must not have a difference in stubs.
I'm very sad about the the unavailability of WC as a package. Not willing to do manual job!!!

**Comment by szepeviktor** [comment]
@timnolte Please contact the WC release team. Open an issue there.

But pleeeease-pleeeese do not mention me. I've **given up** helping them.

**Comment by timnolte** [comment]
Ah, OK, I didn't realize. ☹️ I really appreciate your time and efforts. Thanks!
