### ISSUE TITLE
💡 Releases are temporarily unavailable

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/woocommerce-stubs#13]
...as WC couldn't be installed with Composer.
https://github.com/woocommerce/woocommerce/releases/tag/6.1.0

**Comment by timnolte** [comment]
@szepeviktor so do I understand this correctly that basically at this point the WC Stubs is basically a dead package now?

**Comment by szepeviktor** [comment]
If you ask me kindly I could make a release from the plugin zip.

**Comment by szepeviktor** [comment]
Leave me alone. I'm crying.

Moved to WP.org downloads: https://github.com/php-stubs/woocommerce-stubs/commit/1d9cdae06c783594cbdd6315fcd58371cb3970d8#diff-d56f17dfc9472d218c7792d54878124755811deb217935b5af9ed564f0f830ac

**Comment by timnolte** [comment]
@szepeviktor well, I was looking through and trying to understand what had happened with the WooCommerce package. I have been installing WooCommerce in my own plugin project for development, and then also static analysis, but was looking to move to the stubs.

Anyways, thanks for all of your work!

**Comment by szepeviktor** [comment]
> what had happened with the WooCommerce package

The downloads per day value is about 1 to 1 zillion for Packagist vs. WP.org Plugin Directory.
I suspect Composer support is a very low priority for the WC team.

**Comment by szepeviktor** [comment]
💡 FYI Stubs are needed as there is no autoloader for WP and WC (because they are much closer to being a PHP4 application than a package).
