### ISSUE TITLE
CouponsMovedTrait not found

### ISSUE THREAD

**Issue by seostudio** [php-stubs/woocommerce-stubs#15]
Hi,

we have fatal error: 
`Fatal error: Trait 'Automattic\WooCommerce\Internal\Admin\CouponsMovedTrait' not found in /abc/vendor/php-stubs/woocommerce-stubs/woocommerce-packages-stubs.php on line 17764`

**Comment by szepeviktor** [comment]
Hello Grzegorz! 👋 

Yes, this is a sea of feces.
Please add that [trait from WC's source](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/CouponsMovedTrait.php).
This project should be closed for good.

Reported something very close to your problem: https://github.com/woocommerce/woocommerce/pull/32836

**Comment by szepeviktor** [comment]
@timnolte You see?! WC is a never-ending rabbit hole. 🐇

**Comment by szepeviktor** [comment]
I've released v6.6.0 but don't know why.

**Comment by szepeviktor** [comment]
@seostudio Resolved :)
https://github.com/php-stubs/woocommerce-stubs/commit/c3dc6d41450680436a6f28bd7f906e2e6e807fc2
