### ISSUE TITLE
I cannot get it to work with VSCode PHP Intelephense!

### ISSUE THREAD

**Issue by bgrrota** [php-stubs/woocommerce-stubs#17]
Hi,

First of all thank you for making our life easier, the ACF stubs are working perfectly but not the WooCommerce ones the functions are not recognized at every WooCommerce function i get the Undefined function error message!

Can you please help me with this because it's been months that i am trying to fix it but i cannot find any solution for it!

Thanks and Regards!

**Comment by szepeviktor** [comment]
> it's been months that i am trying to fix it

Hello @bgrrota! Why didn't you open an issue on day one? :)

I use no IDE but I've heard about Intelephense.
https://github.com/bmewburn/vscode-intelephense/issues/1627 may help.

I haven't thought people are talking about my work so much! https://github.com/bmewburn/vscode-intelephense/issues?q=woocommerce-stubs

**Comment by bgrrota** [comment]
Hello @szepeviktor,

Your reply already fixed my issue, I followed this @onetrev solution steps and now it's fixed!

Solution link: [https://github.com/bmewburn/vscode-intelephense/issues/1961#issuecomment-1001134446](https://github.com/bmewburn/vscode-intelephense/issues/1961#issuecomment-1001134446)

Thank you!
