### ISSUE TITLE
Undefined function woocommerce

### ISSUE THREAD

**Issue by joeldasc** [php-stubs/woocommerce-stubs#24]
Hello good morning, the woocommerce functions are not being recognized despite having configured the stubs, my editor is vscode and I am on an ubuntu linux machine.
![Captura desde 2023-08-22 10-54-59](https://github.com/php-stubs/woocommerce-stubs/assets/21370599/b61a52f6-6de4-41f8-a463-5cc7efe69749)
![Captura desde 2023-08-22 10-58-12](https://github.com/php-stubs/woocommerce-stubs/assets/21370599/d4539c53-b7d2-4520-888c-2479dafcbeb4)
![Captura desde 2023-08-22 10-58-53](https://github.com/php-stubs/woocommerce-stubs/assets/21370599/1f0a2e0f-4f53-40f5-84fb-04a72715cc6d)

**Comment by szepeviktor** [comment]
Hello Joel! 👋🏻
Thank you for your report!

Which function are you referring to? `is_woocommerce`?

It is on line `woocommerce-stubs.php:80153`

**Comment by joeldasc** [comment]
It doesn't recognize any functions of the woocommerce-stubs.php file

**Comment by szepeviktor** [comment]
I do not use an IDE.
Please see these settings.
https://github.com/bmewburn/vscode-intelephense/issues/892#issuecomment-565852100
https://github.com/bmewburn/vscode-intelephense/issues/805#issuecomment-607743788

**Comment by szepeviktor** [comment]
This is linked from the README of `wordpress-stubs`
https://github.com/bmewburn/intelephense-docs/issues/2

**Comment by joeldasc** [comment]
I solved it by adding this `"intelephense.files.maxSize": 3200000` in vscode. Thank you!
credits: https://github.com/bmewburn/vscode-intelephense/issues/805#issuecomment-607743788

**Comment by szepeviktor** [comment]
All the best to you!
