### ISSUE TITLE
Trait OrderAttributionMeta not found in v8.9.0

### ISSUE THREAD

**Issue by seostudio** [php-stubs/woocommerce-stubs#25]
It seems the generated stub doesnt include trait 'Automattic\WooCommerce\Internal\Traits\OrderAttributionMeta'

**Comment by szepeviktor** [comment]
Thank you @seostudio for using my stubs!
Yes, in woocommerce-stubs.php:65579 it is used.

**Comment by seostudio** [comment]
@szepeviktor Please remove 8.9.0 from packagist: https://packagist.org/packages/php-stubs/woocommerce-stubs

**Comment by szepeviktor** [comment]
@seostudio Done ❌

**Comment by seostudio** [comment]
@szepeviktor Thank you ❤️

**Comment by szepeviktor** [comment]
Adding that class to stubs ...

**Comment by szepeviktor** [comment]
@seostudio Fixed in 2c0bb50
Could you try `dev-master`?

**Comment by TorbenLundsgaard** [comment]
I can confirm that the changes in dev-master has solved the problem

**Comment by szepeviktor** [comment]
Here we go! https://github.com/php-stubs/woocommerce-stubs/releases/tag/v8.9.0
