### ISSUE TITLE
Short functions are missing

### ISSUE THREAD

**Issue by vyskoczilova** [php-stubs/woocommerce-stubs#4]
Hi, great job! 

However, I've found out missing is_account_page(), is_checkout(), wc_logout_url() functions. Any ideas how to get it there?

And one more thing, could you help me how to generate my own stubs for Timber plugin (I haven't found a way to make php-stubs-generator work?

Thanks!
Karolina

**Comment by szepeviktor** [comment]
Hello Karolina!

resolving the [function](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-conditional-functions.php#L165-L174) problem here in this issue

Please call me to receive free support.

What is your preference?

- Slack
- Discord
- Skype
- Hangouts
- w/o registration: https://meet.jit.si/SzepeViktor

**Comment by szepeviktor** [comment]
`is_account_page` is included in WC stubs :)

woocommerce-stubs.php:45894

**Comment by szepeviktor** [comment]
```
# in Timber v1's directory
composer require giacocorsiglia/stubs-generator
vendor/bin/generate-stubs --functions --classes --interfaces --traits --out=timber-stubs.php lib/
```
